// actionTypes.js
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORIES_WITH_LINKS = "SET_CATEGORIES_WITH_LINKS";
export const SET_USER = "SET_USER";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_PREV_ACTIVE_CATEGORY = "SET_PREV_ACTIVE_CATEGORY";
export const SET_CHANGE = "SET_CHANGE";
//
export const SET_MODAL_MODE = "SET_MODAL_MODE";
export const SET_IS_MODAL_OPEN = "SET_IS_MODAL_OPEN";
//
export const SET_CURRENT_LINK_DATA = "SET_CURRENT_LINK_DATA";
export const SET_NEW_LINK_DATA = "SET_NEW_LINK_DATA";
//
export const SET_IS_LOGGED = "SEL_IS_LOGGED";
export const SET_IS_PAID = "SET_IS_PAID";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
//
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_SEARCH_CATEGORY = "SET_SEARCH_CATEGORY";
